source 'https://rubygems.org'

gem 'coffee-script'
gem 'compass'
gem 'companimation'
gem 'jekyll'
gem 'jekyll-assets'
gem 'rack'
gem 'rack-rewrite'
gem 'redcarpet'
gem 'RedCloth'
gem 'sass'
gem 'uglifier'
