#!/usr/bin/env bash
set -e

env RM_STAR_SILENT=true rm -rf _cache/assets
./tasks/jekyll "_config_deploy.yml"
sleep 1

message=$(git log -1 --pretty=%B)

cd ../757rb.org
git checkout gh-pages
git pull
git branch -D gh-pages-stage
git checkout -b gh-pages-stage

cd ../757rb.org-jekyll
rsync -az --delete --exclude '.git' _site/ ../757rb.org

cd ../757rb.org
git add . 
echo "Using commit message:"
echo "$message"
git commit -m "$message"
git checkout gh-pages
git merge gh-pages-stage
git push origin gh-pages
git checkout gh-pages-stage
