#!/usr/bin/env bash
set -e

# Build and deploy to static github repo.

export DEPLOY_757RB=1

mv _config.yml _config_dev.yml
mv _config_deploy.yml _config.yml

./tasks/jekyll 
sleep 1

mv _config.yml _config_dev.yml
mv _config_deploy.yml _config.yml

message=$(git log -1 --pretty=%B)

cd ../757rb.github.org
git checkout gh-pages
git pull
git branch -D gh-pages-stage
git checkout -b gh-pages-stage

cd ../757rb.org
rsync -az --delete --exclude '.git' _site/ ../757rb.github.org

cd ../757rb.github.org
git add . 
echo "Using commit message:"
echo "$message"
git commit -m "$message"
git checkout gh-pages
git merge gh-pages-stage
git push origin gh-pages
git checkout gh-pages-stage
